import Mathlib

set_option autoImplicit false


def Set' := List Nat
def subsetMem (a b : Set') : Bool := a.all (fun x => b.contains x)
def hereditary (f : List Set') : Bool :=
  f.all (fun a => (subsetsOf a).all (fun s => f.contains s))
where
  subsetsOf (a : Set') : List Set' :=
    a.foldl (fun acc x => acc ++ acc.map (fun s => (s.erase x))) [[]] |>.dedup
def pairIntersect (a b : Set') : Bool := a.any (fun x => b.contains x)
def intersecting (f : List Set') : Bool :=
  f.all (fun a => f.all (fun b => pairIntersect a b))
def commonPoint (f : List Set') : Bool :=
  (groundSet.any (fun x => f.all (fun a => a.contains x)))
where groundSet : List Nat := [1,2,3,4,5]
def downsets5 : List (List Set') :=
  -- all hereditary families on ground set {1..5}, generated by enumerating all
  -- subsets of the 31 nonempty subsets as maximal-generator sets, closing downward,
  -- deduplicating; total count is small (Dedekind-style, < 8000 families)
  (allSubsets 5).filterMap (fun gens =>
    let f := downwardClose gens
    if hereditary f then some f else none) |>.dedup
where
  allSubsets (n : Nat) : List (List Set') := subsetsOfPowerset (allNonemptySubsets n)
  allNonemptySubsets (n : Nat) : List Set' :=
    (List.range (2^n - 1)).map (fun m => (List.range n).filter (fun i => m.testBit i) |>.map (fun i => i+1))
  subsetsOfPowerset (l : List Set') : List (List Set') :=
    (List.range (2^l.length)).map (fun m => (l.zipIdx).filter (fun (_, i) => m.testBit i) |>.map fst)
  downwardClose (gens : List Set') : List Set' :=
    gens.foldl (fun acc g => acc ++ subsetsOf g) [[]] |>.dedup
def check_all : Bool :=
  downsets5.all (fun f =>
    intersecting f ==> (f != [] && commonPoint f))
def check_witness : Bool := check_all

theorem msl_fmz_erdos701_campaign_001_R009_L1_star_bound_n_leq_4_a1r1  : check_witness = true := by decide

-- axiom footprint
#print axioms Set'
#print axioms subsetMem
#print axioms hereditary
#print axioms pairIntersect
#print axioms intersecting
#print axioms commonPoint
#print axioms downsets5
#print axioms check_all
#print axioms check_witness
#print axioms msl_fmz_erdos701_campaign_001_R009_L1_star_bound_n_leq_4_a1r1
