/-
  Erdos problem 1135 = the Collatz conjecture.

  Frozen source: FormalConjectures/ErdosProblems/1135.lean, which is
    `theorem erdos_1135 : type_of% CollatzConjecture.collatz_conjecture`
  and CollatzConjecture.lean freezes

      def collatzStep (n : Nat) : Nat := if Even n then n / 2 else 3 * n + 1
      theorem collatz_conjecture (n : Nat) (hn : n > 0) :
        exists m, collatzStep^[m] n = 1

  THIS FILE DOES NOT PROVE THE CONJECTURE.  It banks sorry-free FRAGMENTS:
  a two-way descent reduction, residue-class descent certificates that are
  uniform in the class parameter (hence universal theorems, not finite
  computations), and the resulting sharpened reduction whose remaining
  hypothesis is confined to four residue classes mod 32.

  READ `RESIDUAL` CORRECTLY.  It names the classes this METHOD does not reach
  at symbolic depth <= 8.  It does NOT say those classes fail to descend, and
  no theorem here says or implies that.  Terras (1976) gives density-one
  finite stopping time, and this file's own scan receipt shows the unreached
  density falling (1/8 at modulus 32, 113/2048 at modulus 4096) at the cost of
  57 certificates instead of 5.  Erdos1135Finite.lean separately certifies by
  kernel computation that every residual n <= 1024 does descend.

  GENERATED by tools/gen_lean.py from receipts/residue-descent-k6.json.
-/
import Mathlib

namespace Erdos1135

/-- Byte-identical to the frozen `CollatzConjecture.collatzStep`. -/
def collatzStep (n : ℕ) : ℕ := if Even n then n / 2 else 3 * n + 1

/-! ### One-step normal forms -/

theorem step_even (m : ℕ) : collatzStep (2 * m) = m := by
  unfold collatzStep
  split
  · omega
  · rename_i h
    rw [Nat.even_iff] at h
    omega

theorem step_odd (m : ℕ) : collatzStep (2 * m + 1) = 6 * m + 4 := by
  unfold collatzStep
  rw [if_neg]
  · ring
  · rw [Nat.even_iff]; omega

theorem step_pos {n : ℕ} (h : 0 < n) : 0 < collatzStep n := by
  unfold collatzStep
  split
  · rename_i he
    rw [Nat.even_iff] at he
    omega
  · omega

theorem iterate_pos (k : ℕ) {n : ℕ} (h : 0 < n) : 0 < collatzStep^[k] n := by
  induction k generalizing n with
  | zero => simpa using h
  | succ k ih => rw [Function.iterate_succ_apply]; exact ih (step_pos h)

/-! ### The descent reduction, both directions (universal) -/

/-- If every `n > 1` eventually drops strictly below itself, the Collatz
conjecture holds. -/
theorem collatz_of_descent
    (H : ∀ n, 1 < n → ∃ k, 0 < k ∧ collatzStep^[k] n < n) :
    ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro hn
    rcases Nat.lt_or_ge n 2 with h1 | h1
    · exact ⟨0, by simp only [Function.iterate_zero_apply]; omega⟩
    · obtain ⟨k, _, hklt⟩ := H n (by omega)
      obtain ⟨m, hm⟩ := ih _ hklt (iterate_pos k (by omega))
      exact ⟨m + k, by rw [Function.iterate_add_apply]; exact hm⟩

/-- Conversely the conjecture gives the descent property, so the reduction is
an equivalence and loses nothing. -/
theorem descent_of_collatz
    (C : ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1) :
    ∀ n, 1 < n → ∃ k, 0 < k ∧ collatzStep^[k] n < n := by
  intro n hn
  obtain ⟨m, hm⟩ := C n (by omega)
  refine ⟨m, ?_, by rw [hm]; omega⟩
  rcases Nat.eq_zero_or_pos m with rfl | hm0
  · rw [Function.iterate_zero_apply] at hm; omega
  · exact hm0

/-! ### Residue-class descent certificates (generated from the receipt) -/

/-- Uniform in `j`: 1 step(s) carry `2 * j + 0` to `1 * j + 0`. -/
theorem iter1_mod2_0 (j : ℕ) :
    collatzStep^[1] (2 * j + 0) = 1 * j + 0 := by
  have e0 : collatzStep (2 * j + 0) = 1 * j + 0 := by
    have h : 2 * j + 0 = 2 * (1 * j + 0) := by ring
    rw [h, step_even]
  have hx : collatzStep^[1] (2 * j + 0) = (collatzStep (2 * j + 0)) := rfl
  rw [hx, e0]

/-- Uniform in `j`: 3 step(s) carry `4 * j + 1` to `3 * j + 1`. -/
theorem iter3_mod4_1 (j : ℕ) :
    collatzStep^[3] (4 * j + 1) = 3 * j + 1 := by
  have e0 : collatzStep (4 * j + 1) = 12 * j + 4 := by
    have h : 4 * j + 1 = 2 * (2 * j + 0) + 1 := by ring
    rw [h, step_odd]
    ring
  have e1 : collatzStep (12 * j + 4) = 6 * j + 2 := by
    have h : 12 * j + 4 = 2 * (6 * j + 2) := by ring
    rw [h, step_even]
  have e2 : collatzStep (6 * j + 2) = 3 * j + 1 := by
    have h : 6 * j + 2 = 2 * (3 * j + 1) := by ring
    rw [h, step_even]
  have hx : collatzStep^[3] (4 * j + 1) = (collatzStep (collatzStep (collatzStep (4 * j + 1)))) := rfl
  rw [hx, e0, e1, e2]

/-- Uniform in `j`: 6 step(s) carry `16 * j + 3` to `9 * j + 2`. -/
theorem iter6_mod16_3 (j : ℕ) :
    collatzStep^[6] (16 * j + 3) = 9 * j + 2 := by
  have e0 : collatzStep (16 * j + 3) = 48 * j + 10 := by
    have h : 16 * j + 3 = 2 * (8 * j + 1) + 1 := by ring
    rw [h, step_odd]
    ring
  have e1 : collatzStep (48 * j + 10) = 24 * j + 5 := by
    have h : 48 * j + 10 = 2 * (24 * j + 5) := by ring
    rw [h, step_even]
  have e2 : collatzStep (24 * j + 5) = 72 * j + 16 := by
    have h : 24 * j + 5 = 2 * (12 * j + 2) + 1 := by ring
    rw [h, step_odd]
    ring
  have e3 : collatzStep (72 * j + 16) = 36 * j + 8 := by
    have h : 72 * j + 16 = 2 * (36 * j + 8) := by ring
    rw [h, step_even]
  have e4 : collatzStep (36 * j + 8) = 18 * j + 4 := by
    have h : 36 * j + 8 = 2 * (18 * j + 4) := by ring
    rw [h, step_even]
  have e5 : collatzStep (18 * j + 4) = 9 * j + 2 := by
    have h : 18 * j + 4 = 2 * (9 * j + 2) := by ring
    rw [h, step_even]
  have hx : collatzStep^[6] (16 * j + 3) = (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (16 * j + 3))))))) := rfl
  rw [hx, e0, e1, e2, e3, e4, e5]

/-- Uniform in `j`: 8 step(s) carry `32 * j + 11` to `27 * j + 10`. -/
theorem iter8_mod32_11 (j : ℕ) :
    collatzStep^[8] (32 * j + 11) = 27 * j + 10 := by
  have e0 : collatzStep (32 * j + 11) = 96 * j + 34 := by
    have h : 32 * j + 11 = 2 * (16 * j + 5) + 1 := by ring
    rw [h, step_odd]
    ring
  have e1 : collatzStep (96 * j + 34) = 48 * j + 17 := by
    have h : 96 * j + 34 = 2 * (48 * j + 17) := by ring
    rw [h, step_even]
  have e2 : collatzStep (48 * j + 17) = 144 * j + 52 := by
    have h : 48 * j + 17 = 2 * (24 * j + 8) + 1 := by ring
    rw [h, step_odd]
    ring
  have e3 : collatzStep (144 * j + 52) = 72 * j + 26 := by
    have h : 144 * j + 52 = 2 * (72 * j + 26) := by ring
    rw [h, step_even]
  have e4 : collatzStep (72 * j + 26) = 36 * j + 13 := by
    have h : 72 * j + 26 = 2 * (36 * j + 13) := by ring
    rw [h, step_even]
  have e5 : collatzStep (36 * j + 13) = 108 * j + 40 := by
    have h : 36 * j + 13 = 2 * (18 * j + 6) + 1 := by ring
    rw [h, step_odd]
    ring
  have e6 : collatzStep (108 * j + 40) = 54 * j + 20 := by
    have h : 108 * j + 40 = 2 * (54 * j + 20) := by ring
    rw [h, step_even]
  have e7 : collatzStep (54 * j + 20) = 27 * j + 10 := by
    have h : 54 * j + 20 = 2 * (27 * j + 10) := by ring
    rw [h, step_even]
  have hx : collatzStep^[8] (32 * j + 11) = (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (32 * j + 11))))))))) := rfl
  rw [hx, e0, e1, e2, e3, e4, e5, e6, e7]

/-- Uniform in `j`: 8 step(s) carry `32 * j + 23` to `27 * j + 20`. -/
theorem iter8_mod32_23 (j : ℕ) :
    collatzStep^[8] (32 * j + 23) = 27 * j + 20 := by
  have e0 : collatzStep (32 * j + 23) = 96 * j + 70 := by
    have h : 32 * j + 23 = 2 * (16 * j + 11) + 1 := by ring
    rw [h, step_odd]
    ring
  have e1 : collatzStep (96 * j + 70) = 48 * j + 35 := by
    have h : 96 * j + 70 = 2 * (48 * j + 35) := by ring
    rw [h, step_even]
  have e2 : collatzStep (48 * j + 35) = 144 * j + 106 := by
    have h : 48 * j + 35 = 2 * (24 * j + 17) + 1 := by ring
    rw [h, step_odd]
    ring
  have e3 : collatzStep (144 * j + 106) = 72 * j + 53 := by
    have h : 144 * j + 106 = 2 * (72 * j + 53) := by ring
    rw [h, step_even]
  have e4 : collatzStep (72 * j + 53) = 216 * j + 160 := by
    have h : 72 * j + 53 = 2 * (36 * j + 26) + 1 := by ring
    rw [h, step_odd]
    ring
  have e5 : collatzStep (216 * j + 160) = 108 * j + 80 := by
    have h : 216 * j + 160 = 2 * (108 * j + 80) := by ring
    rw [h, step_even]
  have e6 : collatzStep (108 * j + 80) = 54 * j + 40 := by
    have h : 108 * j + 80 = 2 * (54 * j + 40) := by ring
    rw [h, step_even]
  have e7 : collatzStep (54 * j + 40) = 27 * j + 20 := by
    have h : 54 * j + 40 = 2 * (27 * j + 20) := by ring
    rw [h, step_even]
  have hx : collatzStep^[8] (32 * j + 23) = (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (collatzStep (32 * j + 23))))))))) := rfl
  rw [hx, e0, e1, e2, e3, e4, e5, e6, e7]


/-! ### The residual obstruction -/

/-- The residue classes mod 32 UNREACHED by the uniform-in-`j` symbolic
method at depth at most 8. Unreached density 4/32.

This is a property of the METHOD, not of the trajectories: nothing here claims
these classes fail to descend, and no theorem in this file says so. -/
def RESIDUAL (n : ℕ) : Prop := n % 32 = 7 ∨ n % 32 = 15 ∨ n % 32 = 27 ∨ n % 32 = 31


/-- The reduction sharpened by the 5 generated certificates: only the
residue classes in `RESIDUAL` still need a descent hypothesis supplied. -/
theorem collatz_of_residual_descent
    (H : ∀ n, 1 < n → RESIDUAL n → ∃ k, 0 < k ∧ collatzStep^[k] n < n) :
    ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1 := by
  apply collatz_of_descent
  intro n hn
  by_cases h0 : n % 2 = 0
  · refine ⟨1, by norm_num, ?_⟩
    obtain ⟨j, hj⟩ : ∃ j, n = 2 * j + 0 := ⟨n / 2, by omega⟩
    rw [hj, iter1_mod2_0]
    omega
  by_cases h1 : n % 4 = 1
  · refine ⟨3, by norm_num, ?_⟩
    obtain ⟨j, hj⟩ : ∃ j, n = 4 * j + 1 := ⟨n / 4, by omega⟩
    rw [hj, iter3_mod4_1]
    omega
  by_cases h2 : n % 16 = 3
  · refine ⟨6, by norm_num, ?_⟩
    obtain ⟨j, hj⟩ : ∃ j, n = 16 * j + 3 := ⟨n / 16, by omega⟩
    rw [hj, iter6_mod16_3]
    omega
  by_cases h3 : n % 32 = 11
  · refine ⟨8, by norm_num, ?_⟩
    obtain ⟨j, hj⟩ : ∃ j, n = 32 * j + 11 := ⟨n / 32, by omega⟩
    rw [hj, iter8_mod32_11]
    omega
  by_cases h4 : n % 32 = 23
  · refine ⟨8, by norm_num, ?_⟩
    obtain ⟨j, hj⟩ : ∃ j, n = 32 * j + 23 := ⟨n / 32, by omega⟩
    rw [hj, iter8_mod32_23]
    omega
  · exact H n hn (by unfold RESIDUAL; omega)


/-! ### Powers of two -/

theorem reaches_one_pow_two (k : ℕ) : ∃ m, collatzStep^[m] (2 ^ k) = 1 := by
  induction k with
  | zero => exact ⟨0, by norm_num⟩
  | succ k ih =>
    obtain ⟨m, hm⟩ := ih
    refine ⟨m + 1, ?_⟩
    rw [Function.iterate_succ_apply, show (2:ℕ) ^ (k + 1) = 2 * 2 ^ k by ring,
      step_even]
    exact hm

/-! ### The frozen target, exactly as declared, under the residual hypothesis -/

/-- The frozen `collatz_conjecture` signature, discharged from the residual
descent hypothesis on the four classes of `RESIDUAL`. -/
theorem frozen_target_of_residual_descent
    (H : ∀ n, 1 < n → RESIDUAL n → ∃ k, 0 < k ∧ collatzStep^[k] n < n)
    (n : ℕ) (hn : n > 0) : ∃ m, collatzStep^[m] n = 1 :=
  collatz_of_residual_descent H n hn


/-! ### Axiom audit -- the kernel stamps the footprint, not the speaker (MSL L32). -/

#print axioms step_even
#print axioms step_odd
#print axioms step_pos
#print axioms iterate_pos
#print axioms collatz_of_descent
#print axioms descent_of_collatz
#print axioms iter1_mod2_0
#print axioms iter3_mod4_1
#print axioms iter6_mod16_3
#print axioms iter8_mod32_11
#print axioms iter8_mod32_23
#print axioms collatz_of_residual_descent
#print axioms reaches_one_pow_two
#print axioms frozen_target_of_residual_descent


end Erdos1135
