#!/usr/bin/env python3
"""
gen_lean.py -- emit the Lean fragment for Erdos 1135 DIRECTLY from
receipts/residue-descent-k*.json.

MSL L34 (RETYPED_TOOL_OUTPUT): every affine coefficient, step count and residue
in the Lean file is read from the tool receipt, never hand-typed into the proof
text.  The only hand-written Lean is the SKELETON (definitions, the
strong-induction reduction, the case-split shape).

usage:  python gen_lean.py receipts/residue-descent-k6.json lean/Erdos1135.lean
"""
import json
import sys

HEADER = r'''/-
  Erdos problem 1135 = the Collatz conjecture.

  Frozen source: FormalConjectures/ErdosProblems/1135.lean, which is
    `theorem erdos_1135 : type_of% CollatzConjecture.collatz_conjecture`
  and CollatzConjecture.lean freezes

      def collatzStep (n : Nat) : Nat := if Even n then n / 2 else 3 * n + 1
      theorem collatz_conjecture (n : Nat) (hn : n > 0) :
        exists m, collatzStep^[m] n = 1

  THIS FILE DOES NOT PROVE THE CONJECTURE.  It banks sorry-free FRAGMENTS:
  a two-way descent reduction, residue-class descent certificates that are
  uniform in the class parameter (hence universal theorems, not finite
  computations), and the resulting sharpened reduction whose remaining
  hypothesis is confined to four residue classes mod 32.

  READ `RESIDUAL` CORRECTLY.  It names the classes this METHOD does not reach
  at symbolic depth <= 8.  It does NOT say those classes fail to descend, and
  no theorem here says or implies that.  Terras (1976) gives density-one
  finite stopping time, and this file's own scan receipt shows the unreached
  density falling (1/8 at modulus 32, 113/2048 at modulus 4096) at the cost of
  57 certificates instead of 5.  Erdos1135Finite.lean separately certifies by
  kernel computation that every residual n <= 1024 does descend.

  GENERATED by tools/gen_lean.py from receipts/residue-descent-k6.json.
-/
import Mathlib

namespace Erdos1135

/-- Byte-identical to the frozen `CollatzConjecture.collatzStep`. -/
def collatzStep (n : ℕ) : ℕ := if Even n then n / 2 else 3 * n + 1

/-! ### One-step normal forms -/

theorem step_even (m : ℕ) : collatzStep (2 * m) = m := by
  unfold collatzStep
  split
  · omega
  · rename_i h
    rw [Nat.even_iff] at h
    omega

theorem step_odd (m : ℕ) : collatzStep (2 * m + 1) = 6 * m + 4 := by
  unfold collatzStep
  rw [if_neg]
  · ring
  · rw [Nat.even_iff]; omega

theorem step_pos {n : ℕ} (h : 0 < n) : 0 < collatzStep n := by
  unfold collatzStep
  split
  · rename_i he
    rw [Nat.even_iff] at he
    omega
  · omega

theorem iterate_pos (k : ℕ) {n : ℕ} (h : 0 < n) : 0 < collatzStep^[k] n := by
  induction k generalizing n with
  | zero => simpa using h
  | succ k ih => rw [Function.iterate_succ_apply]; exact ih (step_pos h)

/-! ### The descent reduction, both directions (universal) -/

/-- If every `n > 1` eventually drops strictly below itself, the Collatz
conjecture holds. -/
theorem collatz_of_descent
    (H : ∀ n, 1 < n → ∃ k, 0 < k ∧ collatzStep^[k] n < n) :
    ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1 := by
  intro n
  induction n using Nat.strong_induction_on with
  | _ n ih =>
    intro hn
    rcases Nat.lt_or_ge n 2 with h1 | h1
    · exact ⟨0, by simp only [Function.iterate_zero_apply]; omega⟩
    · obtain ⟨k, _, hklt⟩ := H n (by omega)
      obtain ⟨m, hm⟩ := ih _ hklt (iterate_pos k (by omega))
      exact ⟨m + k, by rw [Function.iterate_add_apply]; exact hm⟩

/-- Conversely the conjecture gives the descent property, so the reduction is
an equivalence and loses nothing. -/
theorem descent_of_collatz
    (C : ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1) :
    ∀ n, 1 < n → ∃ k, 0 < k ∧ collatzStep^[k] n < n := by
  intro n hn
  obtain ⟨m, hm⟩ := C n (by omega)
  refine ⟨m, ?_, by rw [hm]; omega⟩
  rcases Nat.eq_zero_or_pos m with rfl | hm0
  · rw [Function.iterate_zero_apply] at hm; omega
  · exact hm0

/-! ### Residue-class descent certificates (generated from the receipt) -/
'''

FOOTER = r'''
/-! ### Powers of two -/

theorem reaches_one_pow_two (k : ℕ) : ∃ m, collatzStep^[m] (2 ^ k) = 1 := by
  induction k with
  | zero => exact ⟨0, by norm_num⟩
  | succ k ih =>
    obtain ⟨m, hm⟩ := ih
    refine ⟨m + 1, ?_⟩
    rw [Function.iterate_succ_apply, show (2:ℕ) ^ (k + 1) = 2 * 2 ^ k by ring,
      step_even]
    exact hm

/-! ### The frozen target, exactly as declared, under the residual hypothesis -/

/-- The frozen `collatz_conjecture` signature, discharged from the residual
descent hypothesis on the four classes of `RESIDUAL`. -/
theorem frozen_target_of_residual_descent
    (H : ∀ n, 1 < n → RESIDUAL n → ∃ k, 0 < k ∧ collatzStep^[k] n < n)
    (n : ℕ) (hn : n > 0) : ∃ m, collatzStep^[m] n = 1 :=
  collatz_of_residual_descent H n hn
'''

AXIOM_AUDIT_TAIL = r'''
end Erdos1135
'''


def aff(a: int, b: int) -> str:
    return f"{a} * j + {b}"


def gen_iterate_lemma(cert: dict) -> str:
    mod, r, steps = cert["mod"], cert["r"], cert["steps"]
    trace = [tuple(t) for t in cert["trace"]]
    name = f"iter{steps}_mod{mod}_{r}"
    L = [f"/-- Uniform in `j`: {steps} step(s) carry `{aff(mod, r)}` to "
         f"`{aff(cert['final_a'], cert['final_b'])}`. -/",
         f"theorem {name} (j : ℕ) :",
         f"    collatzStep^[{steps}] ({aff(mod, r)}) = "
         f"{aff(cert['final_a'], cert['final_b'])} := by"]
    for t in range(steps):
        a, b = trace[t]
        a2, b2 = trace[t + 1]
        assert a % 2 == 0, (cert, t)
        L.append(f"  have e{t} : collatzStep ({aff(a, b)}) = {aff(a2, b2)} := by")
        if b % 2 == 0:
            assert (a, b) == (2 * a2, 2 * b2), (cert, t)
            L.append(f"    have h : {aff(a, b)} = 2 * ({aff(a2, b2)}) := by ring")
            L.append("    rw [h, step_even]")
        else:
            x, y = a // 2, (b - 1) // 2
            assert (a2, b2) == (6 * x, 6 * y + 4), (cert, t)
            L.append(f"    have h : {aff(a, b)} = 2 * ({aff(x, y)}) + 1 := by ring")
            L.append("    rw [h, step_odd]")
            L.append("    ring")
    # f^[k] x  is definitionally  f (f (... (f x)))
    expanded = f"({aff(mod, r)})"
    for _ in range(steps):
        expanded = f"(collatzStep {expanded})"
    L.append(f"  have hx : collatzStep^[{steps}] ({aff(mod, r)}) = {expanded} := rfl")
    L.append("  rw [hx, " + ", ".join(f"e{t}" for t in range(steps)) + "]")
    return "\n".join(L) + "\n"


def main() -> None:
    src, dst = sys.argv[1], sys.argv[2]
    data = json.load(open(src, encoding="utf-8"))
    for level in data["levels"]:
        if level["brute_violations_total"] != 0:
            raise SystemExit("REFUSED: brute re-check violations at k=%d" % level["k"])
    certs = [c for L in data["levels"] for c in L["certificates"]]
    last_new_k = max(L["k"] for L in data["levels"] if L["newly_certified"])
    lvl = next(L for L in data["levels"] if L["k"] == last_new_k)
    res_mod = lvl["modulus"]
    residual = sorted(lvl["open_residues"])

    body = [HEADER]
    for c in certs:
        body.append(gen_iterate_lemma(c))

    disj = " ∨ ".join(f"n % {res_mod} = {r}" for r in residual)
    body.append(f"""
/-! ### The residual obstruction -/

/-- The residue classes mod {res_mod} UNREACHED by the uniform-in-`j` symbolic
method at depth at most 8. Unreached density {len(residual)}/{res_mod}.

This is a property of the METHOD, not of the trajectories: nothing here claims
these classes fail to descend, and no theorem in this file says so. -/
def RESIDUAL (n : ℕ) : Prop := {disj}
""")

    L = [f"""
/-- The reduction sharpened by the {len(certs)} generated certificates: only the
residue classes in `RESIDUAL` still need a descent hypothesis supplied. -/
theorem collatz_of_residual_descent
    (H : ∀ n, 1 < n → RESIDUAL n → ∃ k, 0 < k ∧ collatzStep^[k] n < n) :
    ∀ n, 0 < n → ∃ m, collatzStep^[m] n = 1 := by
  apply collatz_of_descent
  intro n hn"""]
    for i, c in enumerate(certs):
        mod, r, steps = c["mod"], c["r"], c["steps"]
        name = f"iter{steps}_mod{mod}_{r}"
        L.append(f"  by_cases h{i} : n % {mod} = {r}")
        L.append(f"  · refine ⟨{steps}, by norm_num, ?_⟩")
        L.append(f"    obtain ⟨j, hj⟩ : ∃ j, n = {mod} * j + {r} := ⟨n / {mod}, by omega⟩")
        L.append(f"    rw [hj, {name}]")
        L.append("    omega")
    L.append("  · exact H n hn (by unfold RESIDUAL; omega)")
    body.append("\n".join(L) + "\n")
    body.append(FOOTER)

    banked = (["step_even", "step_odd", "step_pos", "iterate_pos",
               "collatz_of_descent", "descent_of_collatz"]
              + [f"iter{c['steps']}_mod{c['mod']}_{c['r']}" for c in certs]
              + ["collatz_of_residual_descent", "reaches_one_pow_two",
                 "frozen_target_of_residual_descent"])
    audit = ["\n/-! ### Axiom audit -- the kernel stamps the footprint, "
             "not the speaker (MSL L32). -/\n"]
    audit += [f"#print axioms {n}" for n in banked]
    body.append("\n".join(audit) + "\n")
    body.append(AXIOM_AUDIT_TAIL)

    with open(dst, "w", encoding="utf-8") as f:
        f.write("\n".join(body))

    print(json.dumps({
        "generated_from": src,
        "output": dst,
        "certificates": [{"mod": c["mod"], "r": c["r"], "steps": c["steps"],
                          "final_a": c["final_a"], "final_b": c["final_b"],
                          "jmin": c["jmin"]} for c in certs],
        "residual_modulus": res_mod,
        "residual_residues": residual,
        "residual_density": f"{len(residual)}/{res_mod}",
        "scanned_to_modulus": data["levels"][-1]["modulus"],
        "open_at_deepest_scan": data["levels"][-1]["open_residues"],
        "banked_declarations": banked,
    }, indent=1))


if __name__ == "__main__":
    main()
