/-
  C5 avoidance: {1, 2, 4, 12, 13, 14, 15} (size 7)
  Relation: 5th finite difference coefficients [1, -5, 10, -10, 5, -1]
  For any 6 chosen elements from the set:
    1*x1 -5*x2 +10*x3 -10*x4 +5*x5 -1*x6 != 0
  C(7,6) = 7 6-tuples. All nonzero.
  Auto-generated by rapid_fire_batch.py. No Mathlib -- pure Lean 4.
-/

def c5 (a b c d e f : Int) : Int := a - 5*b + 10*c - 10*d + 5*e - f

theorem c5_c5_avoidance :
  -- All 7 ordered 6-element subsets of {1, 2, 4, 12, 13, 14, 15}
  c5 1 2 4 12 13 14 ≠ 0 ∧
  c5 1 2 4 12 13 15 ≠ 0 ∧
  c5 1 2 4 12 14 15 ≠ 0 ∧
  c5 1 2 4 13 14 15 ≠ 0 ∧
  c5 1 2 12 13 14 15 ≠ 0 ∧
  c5 1 4 12 13 14 15 ≠ 0 ∧
  c5 2 4 12 13 14 15 ≠ 0 := by native_decide
