/-
  C5 avoidance: {1, 3, 9, 14, 15, 16, 17} (size 7)
  Relation: 5th finite difference coefficients [1, -5, 10, -10, 5, -1]
  For any 6 chosen elements from the set:
    1*x1 -5*x2 +10*x3 -10*x4 +5*x5 -1*x6 != 0
  C(7,6) = 7 6-tuples. All nonzero.
  Auto-generated by rapid_fire_batch.py. No Mathlib -- pure Lean 4.
-/

def c5 (a b c d e f : Int) : Int := a - 5*b + 10*c - 10*d + 5*e - f

theorem c5_c5_avoidance :
  -- All 7 ordered 6-element subsets of {1, 3, 9, 14, 15, 16, 17}
  c5 1 3 9 14 15 16 ≠ 0 ∧
  c5 1 3 9 14 15 17 ≠ 0 ∧
  c5 1 3 9 14 16 17 ≠ 0 ∧
  c5 1 3 9 15 16 17 ≠ 0 ∧
  c5 1 3 14 15 16 17 ≠ 0 ∧
  c5 1 9 14 15 16 17 ≠ 0 ∧
  c5 3 9 14 15 16 17 ≠ 0 := by native_decide
