/- SKELETON: counting-density-lower -- generated by shape_templates.py, do not hand-edit.

   Members (found by structural clustering; filenames and lemma names not consulted):
     oracle/evidence/formalizer-sources/erdos/erdos-339.lean
     oracle/evidence/formalizer-sources/erdos/erdos-449.lean
   mean intra-family similarity 0.7064, 11 declaration shapes common to every member.
   representative (syntax source): oracle/evidence/formalizer-sources/erdos/erdos-449.lean

   TIER 1. Every `sorry` below is a HOLE this family fills differently. Every
   non-sorry declaration was IDENTICAL in every member and should be written
   once, here, instead of once per artifact.
-/
import Mathlib
open Filter Finset
namespace Family_counting_density_lower

noncomputable def countingRatio (S : Set ℕ) (n : ℕ) : ℝ :=
  ((S ∩ Set.Iio n).ncard : ℝ) / (n : ℝ)

noncomputable def lowerDensity (S : Set ℕ) : ℝ := liminf (countingRatio S) atTop

noncomputable def upperDensity (S : Set ℕ) : ℝ := limsup (countingRatio S) atTop

-- HOLE (counting-density-lower): supplied per artifact.
theorem lowerDensity_empty : lowerDensity (∅ : Set ℕ) = 0 := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem countingRatio_nonneg (S : Set ℕ) (n : ℕ) : 0 ≤ countingRatio S n := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem countingRatio_le_one (S : Set ℕ) (n : ℕ) : countingRatio S n ≤ 1 := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem lowerDensity_eq_sSup (S : Set ℕ) : lowerDensity S = sSup {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), a ≤ countingRatio S n} := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem upperDensity_eq_sInf (S : Set ℕ) : upperDensity S = sInf {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), countingRatio S n ≤ a} := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem liminfSet_nonempty (S : Set ℕ) : {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), a ≤ countingRatio S n}.Nonempty := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem liminfSet_bddAbove (S : Set ℕ) : BddAbove {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), a ≤ countingRatio S n} := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem limsupSet_nonempty (S : Set ℕ) : {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), countingRatio S n ≤ a}.Nonempty := sorry

-- HOLE (counting-density-lower): supplied per artifact.
theorem limsupSet_bddBelow (S : Set ℕ) : BddBelow {a : ℝ | ∀ᶠ n in (atTop : Filter ℕ), countingRatio S n ≤ a} := sorry

end Family_counting_density_lower
