/- SKELETON: locally-rigid-stabilizer -- generated by shape_templates.py, do not hand-edit.

   Members (found by structural clustering; filenames and lemma names not consulted):
     oracle/evidence/formalizer-sources/rubin-algebraic-disjointness.lean
     oracle/evidence/formalizer-sources/rubin-basis-topology.lean
     oracle/evidence/formalizer-sources/rubin-construct-gu.lean
     oracle/evidence/formalizer-sources/rubin-infinite-exponent.lean
   mean intra-family similarity 0.6566, 5 declaration shapes common to every member.
   representative (syntax source): oracle/evidence/formalizer-sources/rubin-construct-gu.lean

   TIER 1. Every `sorry` below is a HOLE this family fills differently. Every
   non-sorry declaration was IDENTICAL in every member and should be written
   once, here, instead of once per artifact.
-/
import Mathlib.Topology.Homeomorph.Defs
import Mathlib.Topology.Separation.Hausdorff
import Mathlib.Algebra.Group.Commutator
import Mathlib.GroupTheory.Commutator.Basic
import Mathlib.GroupTheory.Subgroup.Centralizer
open Set
open scoped commutatorElement
namespace Family_locally_rigid_stabilizer
variable {X : Type*} [TopologicalSpace X]

def supp (g : X ≃ₜ X) : Set X := {p : X | g p ≠ p}

def rsupp (g : X ≃ₜ X) : Set X := interior (closure (supp g))

def rigidStabilizer (G : Subgroup (X ≃ₜ X)) (U : Set X) : Subgroup (X ≃ₜ X) where
  carrier := {g : X ≃ₜ X | g ∈ G ∧ supp g ⊆ U}
  one_mem' := ⟨one_mem G, by
    intro p hp
    exact absurd (Homeomorph.one_apply p) hp⟩
  mul_mem' := by
    rintro a b ⟨haG, haU⟩ ⟨hbG, hbU⟩
    refine ⟨mul_mem haG hbG, ?_⟩
    intro p hp
    by_cases hpb : p ∈ supp b
    · exact hbU hpb
    · refine haU ?_
      have hbp : b p = p := not_not.mp hpb
      simp only [supp, mem_setOf_eq] at hp ⊢
      rw [Homeomorph.mul_apply, hbp] at hp
      exact hp
  inv_mem' := by
    rintro a ⟨haG, haU⟩
    refine ⟨inv_mem haG, ?_⟩
    intro p hp
    refine haU ?_
    simp only [supp, mem_setOf_eq] at hp ⊢
    intro hap
    exact hp (by
      rw [Homeomorph.inv_apply, ← hap, Homeomorph.symm_apply_apply]
      exact hap.symm)

-- HOLE (locally-rigid-stabilizer): supplied per artifact.
def LocallyMoving (G : Subgroup (X ≃ₜ X)) : Prop := sorry

-- HOLE (locally-rigid-stabilizer): supplied per artifact.
example : supp (1 : X ≃ₜ X) = (∅ : Set X) := sorry

-- HOLE (locally-rigid-stabilizer): supplied per artifact.
example (G : Subgroup (X ≃ₜ X)) : rigidStabilizer G (Set.univ : Set X) = G := sorry

end Family_locally_rigid_stabilizer
