/- SKELETON: motif-nodefs-c96b71 -- generated by shape_templates.py, do not hand-edit.

   Members (found by structural clustering; filenames and lemma names not consulted):
     oracle/evidence/formalizer-sources/Brauer.lean
     oracle/evidence/formalizer-sources/Brauer_route2.lean
   motif similarity 1.0 (mutual nearest neighbours); only 1 declaration shapes are common to both.
   representative (syntax source): oracle/evidence/formalizer-sources/Brauer.lean

   TIER 2 -- MOTIF ONLY. These artifacts build the same constructs out of the same
   argument and result types, but their signatures DIFFER IN ARITY, so there is no
   verbatim shared scaffolding to lift. EVERYTHING below is therefore a hole, taken
   from the more general member. Treat this as a checklist of the constructs the
   motif always needs, NOT as code that has been proved once already.
-/
import Mathlib
open Matrix Polynomial

namespace Family_motif_nodefs_c96b71

-- HOLE (motif-nodefs-c96b71): supplied per artifact.
private lemma det_rank_one_upd {n : ℕ} {N : Matrix (Fin n) (Fin n) ℂ} (h : IsUnit N.det) (u v : Fin n → ℂ) : (N + vecMulVec u v).det = N.det * (1 + v ⬝ᵥ (N⁻¹ *ᵥ u)) := sorry

-- HOLE (motif-nodefs-c96b71): supplied per artifact.
theorem charpoly_roots_rank_one_update {n : ℕ} (A : Matrix (Fin n) (Fin n) ℂ) (lam : ℂ) (s : Multiset ℂ) (hA : A.charpoly.roots = lam ::ₘ s) (x : Fin n → ℂ) (hx : x ≠ 0) (hxe : A.mulVec x = lam • x) (y : Fin n → ℂ) : (A + Matrix.vecMulVec x (star y)).charpoly.roots = (lam + dotProduct (star y) x) ::ₘ s := sorry

end Family_motif_nodefs_c96b71
